name: Selenium Tests

on:
  push:
    branches:
      - main  # Runs tests on every push to the main branch
  pull_request:
    branches:
      - main  # Runs tests on pull requests targeting the main branch
  workflow_dispatch:  # Allows manual triggering from GitHub Actions UI

jobs:
  selenium-test:
    runs-on: ubuntu-latest  # Runs the job on a Linux virtual machine

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Clones the repository

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11.9'  # Use Python 3.9 (or another compatible version)

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium pytest

      - name: Set up Chrome for Selenium
        run: |
          sudo apt update
          sudo apt install -y google-chrome-stable
          CHROME_VERSION=$(google-chrome --version)
          echo "Installed Chrome version: $CHROME_VERSION"

      - name: Set up ChromeDriver
        run: |
          CHROME_DRIVER_VERSION=$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE)
          wget -N https://chromedriver.storage.googleapis.com/$CHROME_DRIVER_VERSION/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          chromedriver --version

      - name: Run Selenium tests in headless mode
        run: |
          python test_openwebui.py
        env:
          DISPLAY: :99  # Required for headless execution
